# Config file for automatic testing at travis-ci.org

language: python

python:
    - "3.4"
    - "3.3"
    - "2.7"
    - "2.6"
    - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
    - pip install -r requirements.txt
    - pip install coverage coveralls nose responses

# command to run tests, e.g. python setup.py test
script: nosetests --with-coverage --cover-package=robobrowser

after_success: coveralls
