
title_category = (
        "Antiques, Art & Collectibles",
        "Appliances",
        "Baby stuff",
        "Books",
        "Blu-Rays, DVDs & CDs",
        "Cell Phones",
        "Computers",
        "Electronics",
        "Free Stuff",
        "Furniture",
        "Garage / Yard sales",
        "Home, Farm & Garden",
        "Jewelry",
        "Motorvehicles : Cars, Trucks, Motorcycles & RVs",
        "Musical instruments & equipment",
        "Office, Commercial & Business",
        "Pets",
        "Shoes, Clothes & Watches",
        "Sporting Goods",
        "Tickets",
        "Toys & Games",
        "Video Gaming")