from enum import Enum

css_element = 'radio'


class CraigslistCategory(Enum):
    antiques = "ata"
    appliances = "ppa"
    arts_crafts = "ara"
    atvs_utvs_snowmobiles = ""
    auto_parts = "pta"
    baby_kid_stuff = "baa"
    bicycle_parts = "bia"
    bicycles = "bia"
    boats = "boo"
    books_magazines = "bka"
    business_commercial = "bfa"
    cars_trucks = "cta"
    cds_dvds_vhs = "ema"
    cell_phones = "moa"
    clothing_accessories = "cla"
    collectibles = "cba"
    computer_parts = "sya"
    computers = "sya"
    electronics = "ela"
    farm_garden = "gra"
    free_stuff = "zip"
    furniture = "fua"
    garage_moving_sales = "gms"
    general_sale = "foa"
    health_beauty = "haa"
    household_items = "hsa"
    jewelry = "jwa"
    materials = "maa"
    motorcycle_parts = "mca"
    motorcycles_scooters = "mca"
    musical_instruments = "msa"
    photo_video = "pha"
    rvs = "rva"
    sporting_goods = "sga"
    tickets = "tia"
    tools = "tla"
    toys_games = "taa"
    video_gaming = "vga"